# This is a comment.
runtime: nodejs14

env: standard

instance_class: B1

handlers:
- url: /
  static_files: dist/gcp-ng-app/browser/index.html
  upload: dist/gcp-ng-app/browser/index.html

- url: /
  static_dir: dist/gcp-ng-app/browser

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

inbound_services:
- warmup

basic_scaling:
  max_instances: 2
  idle_timeout: 150s
