runtime: nodejs14

env: standard

instance_class: F2

handlers:
  - url: /
    static_files: dist/gcp-ng-app/browser/index.html
    require_matching_file: false
    upload: dist/gcp-ng-app/browser/index.html

  - url: /(.*)
    static_files: dist/gcp-ng-app/browser/\1
    require_matching_file: false
    upload: dist/gcp-ng-app/browser/.*

  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: '301'

  - url: .*
    script: auto

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}
